data_path: "data" # Relative to project root
log_file_path: "logs/agent.log"
log_level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
yfinance:
  default_period: "1y" # Default period to fetch if not specified
  default_interval: "1d" # Default interval